---
# ansible-playbook playbook-debian.yml -u admin --private-key=/path/to/private/key -i "$ip,"
- name: copy files to remote server
  hosts: all
  tasks:
  # OS
  - name: update packages and install lsof
    become: true
    package:
      # This is weird in that it does not exist in the offical docs 
      # but this module just passes params down to the underlying 
      # package manager module where `update_cache` is normally a thing so
      # it ends up working....
      update_cache: yes
      state: latest
      name:
        - lsof
        - util-linux # Ensure that fallocate is installed

  - name: create log file
    become: true
    file:
      path: /var/log/fallocate.log
      state: touch
      owner: admin
      group: admin

  - name: cronjob
    cron:
      name: "reboot"
      special_time: reboot
      job: "/home/admin/badlog.py &"
  
  # check.sh
  - name: Create /home/admin/agent directory
    ansible.builtin.file:
      path: /home/admin/agent
      owner: admin
      group: admin
      mode: a+wx
      state: directory

  - name: Copy georgetown systemd files
    become: true
    copy:
      src: {{ item.src }}
      dest: {{ item.dest }}
    with_items:
      - { src: ../files/mock-build.service, dest: /etc/systemd/system/mock-build.service }
      - { src: ../files/secondary-service.service, dest: /etc/systemd/system/secondary-service.service }

  - name: Start mock build application
    become: true
    systemd:
      name: mock-build
      state: started

  - name: Start secondary service
    become: true
    systemd:
      name: secondary-service
      state: started
      enabled: yes

  - name: copy check.sh
    copy:
      src: ../files/check.sh
      dest: /home/admin/agent/check.sh

  - name: set check.sh
    file:
      path: /home/admin/agent/check.sh
      mode: "+x"
